export const SAVE_PROJECT_REQUEST = "SAVE_PROJECT_REQUEST";
export const FETCH_PROJECT_REQUEST = "FETCH_PROJECT_REQUEST";
export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const FETCH_ALL_PROJECT_REQUEST = "FETCH_ALL_PROJECT_REQUEST";
export const PROJECT_SUCCESS = "PROJECT_SUCCESS";
export const PROJECT_FAILURE = "PROJECT_FAILURE";